import Script from 'next/script'
import Head from 'next/head'
import Footer from './Footer'
import Header from './header/index'

function Layout({ children, title }: any) {
  return (
    <div className="content">
      <Head>
        <title>{title ? title + ' - Web' : 'Web'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className='mt-[55px]'>{children}</main>

      <Footer />
    </div>
  )
}

export default Layout
