import Script from 'next/script'
import Head from 'next/head'
import { ReactNode } from 'react'
import Footer from './Footer'
import Header from './header/index'
import { Html } from 'next/document'

function Layout({ children, title }: any) {
  return (
    <div className="content">
      <Head>
        <title>{title ? title + ' - Web' : 'Web'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="node_modules/tw-elements/dist/js/index.min.js"></Script>
      </Head>
      <Header />

      <main>{children}</main>

      <Footer />
    </div>
  )
}

export default Layout
